In [4]:
from FyeldGenerator import generate_field

from matplotlib import use
use('Agg')

import matplotlib.pyplot as plt
import numpy as np



plt.figure()

# Helper that generates power-law power spectrum
def Pkgen(n):
    def Pk(k):
        print(k)
        return np.power(k, -n)

    return Pk

# Draw samples from a normal distribution
def distrib(shape):
    a = np.random.normal(loc=0, scale=1, size=shape)
    b = np.random.normal(loc=0, scale=1, size=shape)
    return a + 1j * b


shape = (512, 512)

field = generate_field(distrib, Pkgen(2), shape)

plt.imshow(field, cmap='jet')

plt.savefig('field.png',dpi=400)
plt.close()

[[0.         0.00195312 0.00390625 ... 0.49609375 0.49804688 0.5       ]
 [0.00195312 0.00276214 0.00436732 ... 0.49609759 0.4980507  0.50000381]
 [0.00390625 0.00436732 0.00552427 ... 0.49610913 0.49806219 0.50001526]
 ...
 [0.00585938 0.00617632 0.00704209 ... 0.49612835 0.49808134 0.50003433]
 [0.00390625 0.00436732 0.00552427 ... 0.49610913 0.49806219 0.50001526]
 [0.00195312 0.00276214 0.00436732 ... 0.49609759 0.4980507  0.50000381]]


<ipython-input-4-400e8e45d663>:17: RuntimeWarning: divide by zero encountered in power
  return np.power(k, -n)


In [5]:
from FyeldGenerator import generate_field
import matplotlib.pyplot as plt
import numpy as np

# Helper that generates power-law power spectrum
def Pkgen(n):
    def Pk(k):
        return np.power(k, -n)

    return Pk

# Draw samples from a normal distribution
def distrib(shape):
    a = np.random.normal(loc=0, scale=1, size=shape)
    b = np.random.normal(loc=0, scale=1, size=shape)
    return a + 1j * b


shape = (512, 512)

field = generate_field(distrib, Pkgen(2), shape)

plt.imshow(field, cmap='seismic')

<ipython-input-5-a37bd22d9ba6>:8: RuntimeWarning: divide by zero encountered in power
  return np.power(k, -n)
